name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          EC2_SECRET_KEY: ${{ secrets.EC2_SECRET_KEY }}
        run: echo "$EC2_SECRET_KEY" > keyfile
        run: chmod 600 keyfile
        run: mkdir -p ~/.ssh
        run: cp known_hosts ~/.ssh/known_hosts
        run: sh  -i keyfile ubuntu@ec2-13-233-109-145.ap-south-1.compute.amazonaws.com  "sudo bash ~/deploy.sh"
