name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          EC2_SECRET_KEY: ${{ secrets.EC2_SECRET_KEY }}
        run: |
          echo "$EC2_SECRET_KEY"  > keyfile
          chmod 600 keyfile
          mkdir -p ~/.ssh
          cp known_hosts ~/.ssh/known_hosts
          pwd
          ls
          cd
          cat .ssh/known_hosts
          ssh -t -i "todo-app-class-2.pem" ubuntu@ec2-3-110-173-232.ap-south-1.compute.amazonaws.com
